message:
  supportedMessageTypes:
    - identify
    - track
    - group
  default:
    transformation:
      spreadMessage: true
      response:
        format: JSON
        method: POST
        endpoint: "https://api.vitally.io/rudderstack"
        headers:
          authorization: "Basic {{ destConfig.apiKey }}"
          content-type: "application/json"